WebApplication2Crud/Models/Category.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApplication2Crud.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Category required")]
        public string Icategory { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Item { get; set; }

        [Required(ErrorMessage = "Reuiured")]
        public string Description { get; set; }

        public DateTime Date { get; set; }

        public int UserId { get; set; }


    }
}

WebApplication2Crud/Models/CategoryDbContext.cs
using System.Data.Entity;

namespace WebApplication2Crud.Models
{
    public class CategoryDbContext : DbContext
    {

        public DbSet<Category> Categories { get; set; }

        public DbSet<Credential> Credentials { get; set; }

    }
}

WebApplication2Crud/Models/Credential.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplication2Crud.Models
{
    public class Credential
    {
        [Key]
        public int id { get; set; }
        [Required(ErrorMessage = "Email Id Required")]
        [EmailAddress(ErrorMessage = "ENter valid mail id")]
        public string EmailId { get; set; }

        [Required(ErrorMessage = "Username Requied")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Password required")]
        public string Password { get; set; }

        public string UserRole { get; set; }




    }
}

WebApplication2Crud/Controllers/CategoryController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using WebApplication2Crud.Models;
using System.Threading.Tasks;
using System.Security.Claims;
using WebApplication2Crud.BuisnessLayer.Interfaces;
using WebApplication2Crud.CommonFactors;

namespace WebApplication2Crud.Controllers
{
    [CustomExceptionFilter]

    public class CategoryController : Controller
    {
        private readonly ICreate _create;
        private readonly IEdit _edit;
        private readonly IPaging _paging;
        private readonly IDetails _details;
        private readonly IDelete _delete;
        public CategoryController(ICreate create, IEdit edit, IPaging paging, IDetails details, IDelete delete)
        {
            _create = create;
            _edit = edit;
            _paging = paging;
            _details = details;
            _delete = delete;
        }

        public ActionResult Index(double b = 5, int a = 1)
        {
            var data = _paging.IndexPagePaging(b, a, out int c);
            ViewBag.TotalPages = Math.Ceiling(c / b);
            return View(data);
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var details = await _details.ProductDetail(id);
            return View(details);
        }

        [Authorize(Roles = "admin,customer")]
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var identity = User.Identity as ClaimsIdentity;
            var claims = identity.Claims;
            var IdentifierName = claims.Where(model => model.Type == ClaimTypes.Name).SingleOrDefault();
            string name = IdentifierName.Value;
            var category = await _create.UserIdentity(name);
            return View(category);
        }

        [HttpPost]
        public async Task<ActionResult> Create(Category Cata)
        {
            if (ModelState.IsValid)
            {
                await _create.AddProductAsync(Cata);
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var details = await _details.ProductDetail(id);
            return View(details);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<ActionResult> Edit(Category data)
        {
            if (ModelState.IsValid)
            {
                await _edit.Update(data);
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            var details = await _details.ProductDetail(id);
            return View(details);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<ActionResult> Delete(int id, Category category)
        {
            await _delete.DeleteItem(id, category);
            return RedirectToAction("Index");
        }
    }
}

WebApplication2Crud/Controllers/CredentialController.cs
using System;
using System.Web;
using System.Web.Mvc;
using WebApplication2Crud.BuisnessLayer.User.Interfaces;
using WebApplication2Crud.Models;

namespace WebApplication2Crud.Controllers
{
    [RequireHttps]
    public class CredentialController : Controller
    {
        private readonly IRegisterUser _registerUser;
        private readonly IAuthentication _authentication;
        public CredentialController(IRegisterUser registerUser, IAuthentication authentication)
        {
            _registerUser = registerUser;
            _authentication = authentication;
        }
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignUp(Credential cd)
        {
            if (_registerUser.IsExist(cd))
            {
                _registerUser.RegisterUserDetails(cd);
                return View("Login");
            }
            else
            {
                ViewBag.message = "Please input correct details";
                return View("SignUp");
            }
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Authenticate(Credential cd)
        {
            var isValid = _authentication.IsValidUser(cd, out string userToken);
            if (isValid)
            {
                Response.Cookies.Set(new HttpCookie("token", userToken));
                return RedirectToAction("Index", "Category");
            }
            else
            {
                ViewBag.message = "Enter Valid User Name & Password";
                return View("Login");
            }
        }

        public ActionResult Logout()
        {
            // FormsAuthentication.SignOut();
            if (Request.Cookies["token"] != null)
            {
                var c = new HttpCookie("token")
                {
                    Expires = DateTime.Now.AddSeconds(1)
                };
                Response.Cookies.Add(c);
            }
            return View("Login");
        }
    }
}

WebApplication2Crud/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebApplication2Crud.BuisnessLayer.Product.Interfaces;
using WebApplication2Crud.Models;

namespace WebApplication2Crud.Controllers
{

    public class ProductController : Controller
    {
        private readonly IShowCategory _showCategory;
        private readonly IShowCategoryItem _showCategoryItem;
        public ProductController(IShowCategory showCategory, IShowCategoryItem showCategoryItem)
        {
            _showCategory = showCategory;
            _showCategoryItem = showCategoryItem;
        }
        public async Task<ActionResult> CategoryWise()
        {
            var list = await _showCategory.AllCategory();
            return View(list);
        }

        public async Task<ActionResult> CategoryWiseView(string category)
        {
            var query = await _showCategoryItem.CategoryItem(category);
            ViewBag.CName = category;
            return View(query);
        }

    }
}

WebApplication2Crud/Controllers/ReportController.cs
using System.Web.Mvc;
using WebApplication2Crud.BuisnessLayer.AdminReport.Interfaces;
using WebApplication2Crud.CommonFactors;

namespace WebApplication2Crud.Controllers
{

    public class ReportController : Controller
    {
        private readonly IReport _report;
        public ReportController(IReport report)
        {
            _report = report;
        }

        [HttpGet]
        [Route("Report")]
        [Authorize(Roles = "admin")]
        [CustFilter]
        public ActionResult ReportByUser()
        {
            var reportList = _report.Report();
            return View(reportList);
        }
    }
}

WebApplication2Crud/Views/Category/Create.cshtml
@model WebApplication2Crud.Models.Category


@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Icategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Item, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserId)
            </div>
        </div>


        @Html.HiddenFor(model => model.Date)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary">Submit</button>

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication2Crud/Views/Category/Delete.cshtml
@model WebApplication2Crud.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Icategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="button" class="btn btn-primary" onclick="window.location= '@Url.Action( "Index", "Category")'">Back</button>
            <button type="submit" class="btn btn-danger">Delete</button>

        </div>
    }
</div>

WebApplication2Crud/Views/Category/Details.cshtml
@model WebApplication2Crud.Models.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Icategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>

    <button type="button" class="btn btn-success" onclick="window.location= '@Url.Action("Edit", "Category", new { id = Model.Id })'">Edit</button>
    <button type="button" class="btn btn-primary" onclick="window.location= '@Url.Action("Index", "Category")'">Back</button>
    <button type="button" class="btn btn-danger" onclick="window.location= '@Url.Action("Delete", "Category", new { id = Model.Id })'">Delete</button>
</p>

WebApplication2Crud/Views/Category/Edit.cshtml
@model WebApplication2Crud.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Icategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Item, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserId)
                @Html.HiddenFor(model => model.Date)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication2Crud/Views/Category/Index.cshtml
    @model IEnumerable<WebApplication2Crud.Models.Category>

@{
    ViewBag.Title = "Index";
}

<h2>All Products</h2>




<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button type="button" class="btn btn-success" onclick="window.location= '@Url.Action("Create", "Category")'">Add New </button>


    <button type="button" class="btn btn-success" onclick="window.location= '@Url.Action("CategoryWise", "Product")'">View Category Wise </button>



    @if (User.Identity.Name == "admin")
    {

        <button type="button" class="btn btn-danger navbar-right" style="margin-top:10px" onclick="window.location= '@Url.Action("ReportByUser", "Report")'">Generate Report</button>


    }


    @*<h4>Select record per pages</h4>
        <select>
            <option> @Html.ActionLink(5.ToString(), "Index", new { b = 5.00 })</option>
            <option> @Html.ActionLink(10.ToString(), "Index", new { b = 10.00 })</option>
            <option> @Html.ActionLink(15.ToString(), "Index", new { b = 15.00 })</option>
        </select>*@
</div>
<br />
<table class="table table-striped">
    <tr>
        <th scope="col">
            CATEGORY
        </th>
        <th scope="col">
            ITEM
        </th>
        <th scope="col">
            DESCRIPTION
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Icategory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Item)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <button type="button" class="btn btn-link" onclick="window.location= '@Url.Action("Edit", "Category", new { id = item.Id })'">Edit</button>
                <button type="button" class="btn btn-link" onclick="window.location= '@Url.Action("Delete", "Category", new { id = item.Id })'">Delete</button>
                <button type="button" class="btn btn-link" onclick="window.location= '@Url.Action("Details", "Category", new { id = item.Id })'">Details</button>


            </td>
        </tr>
    }


</table>





@{


    double totalPages = ViewBag.TotalPages;

    for (int i = 1; i <= totalPages; i++)
    {

        <ul class="pagination">
            <li>
                @Html.ActionLink(i.ToString(), "Index", new { a = i })

            </li>
        </ul>
    }
}

WebApplication2Crud/Views/Credential/Login.cshtml
@model WebApplication2Crud.Models.Credential

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style="color:red">
        @ViewBag.message
    </div>


    @using (Html.BeginForm("Authenticate", "Credential"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h1>Enter Details to Login</h1>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-success" value="LogIn" />
                    <button type="button" class="btn btn-success" onclick="window.location= '@Url.Action("SignUp", "Credential")'">Sign Up </button>

                </div>
            </div>
        </div>
    }


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

WebApplication2Crud/Views/Credential/SignUp.cshtml
@model WebApplication2Crud.Models.Credential

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SignUp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>




    <h1>Enter detials to sign up</h1>

    @using (Html.BeginForm())
    {

        @ViewBag.message

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-horizontal">

            <hr />
            <table>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                </tr>
            </table>

            <br />
            <div class="form-outline mb-4">
                <table>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                        </td>
                    </tr>
                </table>
                <div class="col-md-10">


                </div>
            </div>
            <br />
            <div class="form-group">
                <table>
                    <tr>
                        <td>
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                        </td>
                        <td>
                            @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        </td>
                        @Html.HiddenFor(model => model.UserRole)
                    </tr>
                </table>
                <div class="col-md-10">
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="SignUp" class="btn btn-success" />      <button type="button" class="btn btn-primary" onclick="window.location= '@Url.Action("Login", "Credential")'">Click Here to login </button>
                </div>
            </div>
        </div>
    }
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

WebApplication2Crud/Views/Product/CategoryWise.cshtml
@model IEnumerable<WebApplication2Crud.Models.Category>



@{
    ViewBag.Title = "Index";
}

<h2>All Categories</h2>


<table class="table table-striped">
    <tr>    <th scope="col">CATEGORY</th>  <th scope="col">View All Products</th>  </tr>


    @{
        foreach (var item in Model)
        {
            <tr>
                <td>@item.Icategory</td>
                <td> @Html.ActionLink("View", "CategoryWiseView", new { category = item.Icategory }) </td>



            </tr>
        }
    }


</table>

<button type="button" class="btn btn-primary" onclick="window.location= '@Url.Action("Index", "Category")'">Back</button>

WebApplication2Crud/Views/Product/CategoryWiseView.cshtml
@model IEnumerable<WebApplication2Crud.Models.Category>
@{
    ViewBag.Title = "CategoryWiseView";
}

<h2>@ViewBag.CName</h2>
<table class="table table-striped">
    <tr>
        <th scope="col">
            ITEM List
        </th>
        <th scope="col">
            Details
        </th>
    </tr>

    @{
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Item
                </td>
                <td>

                    <button type="button" class="btn btn-link" onclick="window.location= '@Url.Action("Details", "Category", new { id = item.Id })'">View</button>
                </td>
            </tr>
        }
    }

</table>

<button type="button" class="btn btn-primary" onclick="window.location= '@Url.Action("CategoryWise", "Product")'">Back</button>

WebApplication2Crud/Views/Report/ReportByUser.cshtml
@model IEnumerable<WebApplication2Crud.ViewModel.Report>
@{
    ViewBag.Title = "ReportByUser";
}
<h4>
    @ViewBag.message2
</h4>
<br />

<table class="table table-striped">
    <tr>
        <th>
            CATEGORY
        </th>
        <th>
            ITEM
        </th>
        <th>
            UserName
        </th>
        @*<th>
                Date of created
            </th>*@


    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Icategory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.item)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>*@

        </tr>
    }


</table>

WebApplication2Crud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Category Master", "Index", "Category", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Category")</li>
                    <li>@Html.ActionLink("Create", "Create", "Category")</li>



                    @if (User.Identity.IsAuthenticated)
                    {
                        var username = "Hello     " + @User.Identity.Name.ToUpper();

                        <li class="navbar-right">@Html.ActionLink(username, "Index", "Category")</li>

                    }
                </ul>


                <ul>
                    <li>
                        <button type="button" class="btn btn-danger navbar-right" style="margin-top:10px" onclick="window.location= '@Url.Action("Logout", "Credential")'">Log Out</button>
                    </li>
                </ul>

            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Welcome to Category Master</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>